# Generated by Django 3.2.5 on 2022-02-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_desciption', models.CharField(max_length=250)),
                ('pub_date', models.DateField()),
            ],
        ),

    ]
